---
# This playbook deploys the whole application stack in this site.

# Apply common configuration to all hosts
- hosts: all
  become: yes

  pre_tasks:
    - name: Update APT for Debian
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Install Dependencies for Debian
      apt:
        name: "{{ item }}"
      when: ansible_os_family == 'Debian'
      with_items:
        - git
        - vim
        # - python-pip
        # - python-virtualenv

    - name: Update Yum for RedHat
      yum:
        update_cache: yes
      when: ansible_os_family == 'RedHat'

    - name: Install Dependencies for RedHat
      yum:
        name: "{{ item }}"
      when: ansible_os_family == 'RedHat'
      with_items:
        - vim
        - git
        - python-virtualenv

  vars:
    pip_install_packages:
      - name: docker

  roles:
    - geerlingguy.pip
    - geerlingguy.docker

  tasks:
    - name: Create portainer container
      docker_container:
        name: portainer
        image: portainer/portainer-ce
        state: started
        recreate: yes
        restart_policy: always
        published_ports:
          - "8000:8000"
          - "9000:9000"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - portainer_data:/data

...
