---
# This playbook deploys the whole application stack in this site.

# Apply common configuration to all hosts
- hosts: all
  become: yes

  pre_tasks:
    - name: Update APT for Debian
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Install Dependencies for Debian
      apt:
        name: "{{ item }}"
      when: ansible_os_family == 'Debian'
      with_items:
        - git
        - vim
        # - python-pip
        # - python-virtualenv

    - name: Update Yum for RedHat
      yum:
        update_cache: yes
      when: ansible_os_family == 'RedHat'

    - name: Install Dependencies for RedHat
      yum:
        name: "{{ item }}"
      when: ansible_os_family == 'RedHat'
      with_items:
        - vim
        - git
        - python-virtualenv

  vars:
    pip_install_packages:
      - name: docker

  roles:
    - geerlingguy.pip
    - geerlingguy.docker

  tasks:
    - name: Add user g3rhard
      ansible.builtin.user:
        name: g3rhard
        shell: /bin/bash
        groups: sudo,docker
        append: yes

    - name: Set authorized key for user g3rhard
      ansible.posix.authorized_key:
        user: g3rhard
        state: present
        key: https://github.com/g3rhard.keys

    - name: Allow 'sudo' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'


...
