name: Check Ansible

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Important: This sets up your GITHUB_WORKSPACE environment variable
    - uses: actions/checkout@v2

    - name: Lint Ansible Playbook
      uses: patrickjahns/ansible-later-action@master
      with:
        # config: .later.yml
        path: site.yml
